-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMCCVdob2xlQm9keQZDZW50cmUAAQUAAAECABKjAAAA/wAAAAIAAAD/AQAAAgAAAG8CAACMAwEAxQECAwEAAAD/AgAAAgAAAG8DAQCMBAIAxQIDAwEAAADFAAEDAQAAAIIAAgACAwEDAgABAAEYAAMAAQAAAAAAAQAAAAAAAAAAAQAAAAAA

-- Decompiling is disabled