local Parent = {}
local Value = {}
local function ScaleTo() end
local function PivotTo() end
local function GetPivot() end
local Position = {}
local function Destroy() end
local function Play() end
local type = type
local table = table
local ipairs = ipairs
local Enum = Enum
local EasingStyle = Enum.EasingStyle
local Linear = {}
local EasingDirection = Enum.EasingDirection
local Out = {}
local Sine = {}
local string = string
local lower = string.lower
local expo = {}
local Exponential = {}
local InOut = {}
local TweenInfo = {}
local new = {}
local unpack = {}
local Model = {}
local IsA = {}
local Scale = {}
local Instance = {}
local NumberValue = {}
local function GetScale() end
local Changed = {}
local function Connect() end
local CFrame = {}
local CFrameValue = {}
local Vector3Value = {}
local function Create() end
local Completed = {}
local Once = {}
local task = task
local delay = {}
local insert = table.insert
local game = game
local TweenService = game:GetService("TweenService")
local function GetService() end