local table = table
local clear = table.clear
local math = math
local ceil = math.ceil
local insert = table.insert
local RearrangeTables = {}
local PrimaryPart = {}
local Size = {}
local X = {}
local function GetRowWidth() end
local hidden = {}
local CFrame = {}
local new = {}
local function PivotTo() end
local function hidePet() end
local function GetChildren() end
local Transparency = {}
local function showPet() end
local game = game
local RunService = game:GetService("RunService")
local function GetService() end
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local workspace = game:GetService("Workspace")
local PlayersPets = {}
local function WaitForChild() end
local LocalPlayer = Players.LocalPlayer
local RaycastParams = {}