local assert = assert
local _ = {}
local v24 = {}
local function ToObjectSpace() end
local v29 = {}
local v33 = {}
local Scale = {}
local v36 = {}
local Offset = {}
local Size = {}
local v41 = {}
local Drag = {}
local VelocityInheritance = {}
local Speed = {}
local Acceleration = {}
local ZOffset = {}
local CFrame = CFrame
local v49 = {}
local Model = {}
local IsA = {}
local math = math
local max = math.max
local ScaleTo = {}
local BasePart = {}
local function FindFirstAncestorWhichIsA() end
local PrimaryPart = {}
local AssemblyRootPart = {}
local function GetPivot() end
local new = {}
local ObjectCFrame = {}
local Position = {}
local function ToWorldSpace() end
local function PivotTo() end
local SpecialMesh = {}
local ParticleEmitter = {}
local typeof = typeof
local Vector3 = Vector3
local X = {}
local Y = {}
local Z = {}
local NumberRange = {}
local Min = {}
local Max = {}
local Attachment = {}
local ipairs = ipairs
local function GetChildren() end
local v12 = {}
local require = require
local script = script
local ScaleNumberSequence = {}